# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(527, 321)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(dialog.sizePolicy().hasHeightForWidth())
        dialog.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.user_name_Label = QtWidgets.QLabel(dialog)
        self.user_name_Label.setObjectName("user_name_Label")
        self.horizontalLayout_3.addWidget(self.user_name_Label)
        self.user_name_LineEdit = QtWidgets.QLineEdit(dialog)
        self.user_name_LineEdit.setText("")
        self.user_name_LineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.user_name_LineEdit.setObjectName("user_name_LineEdit")
        self.horizontalLayout_3.addWidget(self.user_name_LineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.password_Label = QtWidgets.QLabel(dialog)
        self.password_Label.setObjectName("password_Label")
        self.horizontalLayout_3.addWidget(self.password_Label)
        self.password_LineEdit = QtWidgets.QLineEdit(dialog)
        self.password_LineEdit.setInputMask("")
        self.password_LineEdit.setText("")
        self.password_LineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_LineEdit.setObjectName("password_LineEdit")
        self.horizontalLayout_3.addWidget(self.password_LineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.intranet_server_ip_Label = QtWidgets.QLabel(dialog)
        self.intranet_server_ip_Label.setObjectName("intranet_server_ip_Label")
        self.horizontalLayout_4.addWidget(self.intranet_server_ip_Label)
        self.intranet_server_ip_LineEdit = QtWidgets.QLineEdit(dialog)
        self.intranet_server_ip_LineEdit.setMaxLength(32762)
        self.intranet_server_ip_LineEdit.setObjectName("intranet_server_ip_LineEdit")
        self.horizontalLayout_4.addWidget(self.intranet_server_ip_LineEdit)
        self.intranet_server_port_Label = QtWidgets.QLabel(dialog)
        self.intranet_server_port_Label.setObjectName("intranet_server_port_Label")
        self.horizontalLayout_4.addWidget(self.intranet_server_port_Label)
        self.intranet_server_port_LineEdit = QtWidgets.QLineEdit(dialog)
        self.intranet_server_port_LineEdit.setObjectName("intranet_server_port_LineEdit")
        self.horizontalLayout_4.addWidget(self.intranet_server_port_LineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.local_proxy_server_prot_Label = QtWidgets.QLabel(dialog)
        self.local_proxy_server_prot_Label.setObjectName("local_proxy_server_prot_Label")
        self.horizontalLayout.addWidget(self.local_proxy_server_prot_Label)
        self.local_proxy_server_port_LineEdit = QtWidgets.QLineEdit(dialog)
        self.local_proxy_server_port_LineEdit.setObjectName("local_proxy_server_port_LineEdit")
        self.horizontalLayout.addWidget(self.local_proxy_server_port_LineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineedit_empty_Label = QtWidgets.QLabel(dialog)
        self.lineedit_empty_Label.setStyleSheet("QLabel{\n"
"    color:red;\n"
"}")
        self.lineedit_empty_Label.setText("")
        self.lineedit_empty_Label.setObjectName("lineedit_empty_Label")
        self.horizontalLayout_6.addWidget(self.lineedit_empty_Label)
        self.login_pushButton = QtWidgets.QPushButton(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_pushButton.sizePolicy().hasHeightForWidth())
        self.login_pushButton.setSizePolicy(sizePolicy)
        self.login_pushButton.setObjectName("login_pushButton")
        self.horizontalLayout_6.addWidget(self.login_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "期权交易端登录界面"))
        self.label.setText(_translate("dialog", "登录远程服务器"))
        self.user_name_Label.setText(_translate("dialog", "用户名"))
        self.user_name_LineEdit.setPlaceholderText(_translate("dialog", "输入账号"))
        self.password_Label.setText(_translate("dialog", "密码"))
        self.password_LineEdit.setPlaceholderText(_translate("dialog", "输入密码"))
        self.intranet_server_ip_Label.setText(_translate("dialog", "连接内网服务器"))
        self.intranet_server_ip_LineEdit.setPlaceholderText(_translate("dialog", "内网服务器IP地址"))
        self.intranet_server_port_Label.setText(_translate("dialog", "端口"))
        self.intranet_server_port_LineEdit.setPlaceholderText(_translate("dialog", "端口号"))
        self.local_proxy_server_prot_Label.setText(_translate("dialog", "本机代理服务器端口"))
        self.local_proxy_server_port_LineEdit.setPlaceholderText(_translate("dialog", "代理服务器端口号"))
        self.login_pushButton.setText(_translate("dialog", "正常登录"))

