# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(561, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(LoginDialog.sizePolicy().hasHeightForWidth())
        LoginDialog.setSizePolicy(sizePolicy)
        LoginDialog.setMinimumSize(QtCore.QSize(561, 300))
        LoginDialog.setMaximumSize(QtCore.QSize(561, 300))
        self.gridLayout_2 = QtWidgets.QGridLayout(LoginDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.password_Label = QtWidgets.QLabel(LoginDialog)
        self.password_Label.setObjectName("password_Label")
        self.gridLayout_2.addWidget(self.password_Label, 2, 2, 1, 1)
        self.intranet_server_port_Label = QtWidgets.QLabel(LoginDialog)
        self.intranet_server_port_Label.setObjectName("intranet_server_port_Label")
        self.gridLayout_2.addWidget(self.intranet_server_port_Label, 3, 2, 1, 1)
        self.intranet_server_ip_LineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.intranet_server_ip_LineEdit.setMaxLength(32762)
        self.intranet_server_ip_LineEdit.setObjectName("intranet_server_ip_LineEdit")
        self.gridLayout_2.addWidget(self.intranet_server_ip_LineEdit, 3, 1, 1, 1)
        self.password_LineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.password_LineEdit.setInputMask("")
        self.password_LineEdit.setText("")
        self.password_LineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_LineEdit.setObjectName("password_LineEdit")
        self.gridLayout_2.addWidget(self.password_LineEdit, 2, 3, 1, 1)
        self.user_name_LineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.user_name_LineEdit.setText("")
        self.user_name_LineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.user_name_LineEdit.setObjectName("user_name_LineEdit")
        self.gridLayout_2.addWidget(self.user_name_LineEdit, 2, 1, 1, 1)
        self.intranet_server_port_LineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.intranet_server_port_LineEdit.setObjectName("intranet_server_port_LineEdit")
        self.gridLayout_2.addWidget(self.intranet_server_port_LineEdit, 3, 3, 1, 1)
        self.user_name_Label = QtWidgets.QLabel(LoginDialog)
        self.user_name_Label.setObjectName("user_name_Label")
        self.gridLayout_2.addWidget(self.user_name_Label, 2, 0, 1, 1)
        self.intranet_server_ip_Label = QtWidgets.QLabel(LoginDialog)
        self.intranet_server_ip_Label.setObjectName("intranet_server_ip_Label")
        self.gridLayout_2.addWidget(self.intranet_server_ip_Label, 3, 0, 1, 1)
        self.local_proxy_server_prot_Label = QtWidgets.QLabel(LoginDialog)
        self.local_proxy_server_prot_Label.setObjectName("local_proxy_server_prot_Label")
        self.gridLayout_2.addWidget(self.local_proxy_server_prot_Label, 4, 0, 1, 1)
        self.local_proxy_server_port_LineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.local_proxy_server_port_LineEdit.setObjectName("local_proxy_server_port_LineEdit")
        self.gridLayout_2.addWidget(self.local_proxy_server_port_LineEdit, 4, 1, 1, 1)
        self.login_pushButton = QtWidgets.QPushButton(LoginDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_pushButton.sizePolicy().hasHeightForWidth())
        self.login_pushButton.setSizePolicy(sizePolicy)
        self.login_pushButton.setObjectName("login_pushButton")
        self.gridLayout_2.addWidget(self.login_pushButton, 5, 3, 1, 1)
        self.lineedit_empty_Label = QtWidgets.QLabel(LoginDialog)
        self.lineedit_empty_Label.setStyleSheet("QLabel{\n"
"    color:red;\n"
"}")
        self.lineedit_empty_Label.setText("")
        self.lineedit_empty_Label.setObjectName("lineedit_empty_Label")
        self.gridLayout_2.addWidget(self.lineedit_empty_Label, 5, 0, 1, 2)
        self.label = QtWidgets.QLabel(LoginDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 4)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "期权交易端登录界面"))
        self.password_Label.setText(_translate("LoginDialog", "密码"))
        self.intranet_server_port_Label.setText(_translate("LoginDialog", "端口"))
        self.intranet_server_ip_LineEdit.setPlaceholderText(_translate("LoginDialog", "内网服务器IP地址"))
        self.password_LineEdit.setPlaceholderText(_translate("LoginDialog", "输入密码"))
        self.user_name_LineEdit.setPlaceholderText(_translate("LoginDialog", "输入账号"))
        self.intranet_server_port_LineEdit.setPlaceholderText(_translate("LoginDialog", "端口号"))
        self.user_name_Label.setText(_translate("LoginDialog", "用户名"))
        self.intranet_server_ip_Label.setText(_translate("LoginDialog", "连接内网服务器"))
        self.local_proxy_server_prot_Label.setText(_translate("LoginDialog", "本机代理服务器端口"))
        self.local_proxy_server_port_LineEdit.setPlaceholderText(_translate("LoginDialog", "代理服务器端口号"))
        self.login_pushButton.setText(_translate("LoginDialog", "正常登录"))
        self.label.setText(_translate("LoginDialog", "登录远程服务器"))

