# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fontAndColorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FontAndColorDialog(object):
    def setupUi(self, FontAndColorDialog):
        FontAndColorDialog.setObjectName("FontAndColorDialog")
        FontAndColorDialog.resize(457, 343)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FontAndColorDialog.sizePolicy().hasHeightForWidth())
        FontAndColorDialog.setSizePolicy(sizePolicy)
        FontAndColorDialog.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(FontAndColorDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.selected_background_color_label = QtWidgets.QLabel(FontAndColorDialog)
        self.selected_background_color_label.setObjectName("selected_background_color_label")
        self.gridLayout.addWidget(self.selected_background_color_label, 4, 0, 1, 1)
        self.content_background_color_label = QtWidgets.QLabel(FontAndColorDialog)
        self.content_background_color_label.setObjectName("content_background_color_label")
        self.gridLayout.addWidget(self.content_background_color_label, 3, 0, 1, 1)
        self.interface_background_color_label = QtWidgets.QLabel(FontAndColorDialog)
        self.interface_background_color_label.setObjectName("interface_background_color_label")
        self.gridLayout.addWidget(self.interface_background_color_label, 2, 0, 1, 1)
        self.font_color_label = QtWidgets.QLabel(FontAndColorDialog)
        self.font_color_label.setObjectName("font_color_label")
        self.gridLayout.addWidget(self.font_color_label, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.selected_background_toolButton = QtWidgets.QToolButton(FontAndColorDialog)
        self.selected_background_toolButton.setObjectName("selected_background_toolButton")
        self.horizontalLayout_7.addWidget(self.selected_background_toolButton)
        self.show_selected_background_label = QtWidgets.QLabel(FontAndColorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_selected_background_label.sizePolicy().hasHeightForWidth())
        self.show_selected_background_label.setSizePolicy(sizePolicy)
        self.show_selected_background_label.setMinimumSize(QtCore.QSize(30, 30))
        self.show_selected_background_label.setText("")
        self.show_selected_background_label.setObjectName("show_selected_background_label")
        self.horizontalLayout_7.addWidget(self.show_selected_background_label)
        self.gridLayout.addLayout(self.horizontalLayout_7, 4, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.interface_background_color_toolButton = QtWidgets.QToolButton(FontAndColorDialog)
        self.interface_background_color_toolButton.setObjectName("interface_background_color_toolButton")
        self.horizontalLayout_3.addWidget(self.interface_background_color_toolButton)
        self.show_interface_background_color_label = QtWidgets.QLabel(FontAndColorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_interface_background_color_label.sizePolicy().hasHeightForWidth())
        self.show_interface_background_color_label.setSizePolicy(sizePolicy)
        self.show_interface_background_color_label.setMinimumSize(QtCore.QSize(30, 30))
        self.show_interface_background_color_label.setText("")
        self.show_interface_background_color_label.setObjectName("show_interface_background_color_label")
        self.horizontalLayout_3.addWidget(self.show_interface_background_color_label)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.font_label = QtWidgets.QLabel(FontAndColorDialog)
        self.font_label.setObjectName("font_label")
        self.gridLayout.addWidget(self.font_label, 0, 0, 1, 1)
        self.warning_background_color_label = QtWidgets.QLabel(FontAndColorDialog)
        self.warning_background_color_label.setObjectName("warning_background_color_label")
        self.gridLayout.addWidget(self.warning_background_color_label, 5, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.warning_background_color_toolButton = QtWidgets.QToolButton(FontAndColorDialog)
        self.warning_background_color_toolButton.setObjectName("warning_background_color_toolButton")
        self.horizontalLayout_8.addWidget(self.warning_background_color_toolButton)
        self.show_warning_background_color_label = QtWidgets.QLabel(FontAndColorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_warning_background_color_label.sizePolicy().hasHeightForWidth())
        self.show_warning_background_color_label.setSizePolicy(sizePolicy)
        self.show_warning_background_color_label.setMinimumSize(QtCore.QSize(30, 30))
        self.show_warning_background_color_label.setText("")
        self.show_warning_background_color_label.setObjectName("show_warning_background_color_label")
        self.horizontalLayout_8.addWidget(self.show_warning_background_color_label)
        self.gridLayout.addLayout(self.horizontalLayout_8, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.font_color_toolButton = QtWidgets.QToolButton(FontAndColorDialog)
        self.font_color_toolButton.setObjectName("font_color_toolButton")
        self.horizontalLayout_2.addWidget(self.font_color_toolButton)
        self.show_font_color_label = QtWidgets.QLabel(FontAndColorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_font_color_label.sizePolicy().hasHeightForWidth())
        self.show_font_color_label.setSizePolicy(sizePolicy)
        self.show_font_color_label.setMinimumSize(QtCore.QSize(30, 30))
        self.show_font_color_label.setText("")
        self.show_font_color_label.setObjectName("show_font_color_label")
        self.horizontalLayout_2.addWidget(self.show_font_color_label)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.content_background_color_toolButton = QtWidgets.QToolButton(FontAndColorDialog)
        self.content_background_color_toolButton.setObjectName("content_background_color_toolButton")
        self.horizontalLayout_4.addWidget(self.content_background_color_toolButton)
        self.show_content_background_color_label = QtWidgets.QLabel(FontAndColorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_content_background_color_label.sizePolicy().hasHeightForWidth())
        self.show_content_background_color_label.setSizePolicy(sizePolicy)
        self.show_content_background_color_label.setMinimumSize(QtCore.QSize(30, 30))
        self.show_content_background_color_label.setText("")
        self.show_content_background_color_label.setObjectName("show_content_background_color_label")
        self.horizontalLayout_4.addWidget(self.show_content_background_color_label)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.show_font_label = QtWidgets.QLabel(FontAndColorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_font_label.sizePolicy().hasHeightForWidth())
        self.show_font_label.setSizePolicy(sizePolicy)
        self.show_font_label.setMinimumSize(QtCore.QSize(250, 30))
        self.show_font_label.setText("")
        self.show_font_label.setObjectName("show_font_label")
        self.horizontalLayout_5.addWidget(self.show_font_label)
        self.font_toolButton = QtWidgets.QToolButton(FontAndColorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.font_toolButton.sizePolicy().hasHeightForWidth())
        self.font_toolButton.setSizePolicy(sizePolicy)
        self.font_toolButton.setObjectName("font_toolButton")
        self.horizontalLayout_5.addWidget(self.font_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_pushButton = QtWidgets.QPushButton(FontAndColorDialog)
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.horizontalLayout.addWidget(self.cancel_pushButton)
        spacerItem7 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.confirm_change_pushButton = QtWidgets.QPushButton(FontAndColorDialog)
        self.confirm_change_pushButton.setObjectName("confirm_change_pushButton")
        self.horizontalLayout.addWidget(self.confirm_change_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(FontAndColorDialog)
        QtCore.QMetaObject.connectSlotsByName(FontAndColorDialog)

    def retranslateUi(self, FontAndColorDialog):
        _translate = QtCore.QCoreApplication.translate
        FontAndColorDialog.setWindowTitle(_translate("FontAndColorDialog", "字体和配色"))
        self.selected_background_color_label.setText(_translate("FontAndColorDialog", "选中背景色"))
        self.content_background_color_label.setText(_translate("FontAndColorDialog", "内容背景色"))
        self.interface_background_color_label.setText(_translate("FontAndColorDialog", "界面背景色"))
        self.font_color_label.setText(_translate("FontAndColorDialog", "字体颜色"))
        self.selected_background_toolButton.setText(_translate("FontAndColorDialog", "..."))
        self.interface_background_color_toolButton.setText(_translate("FontAndColorDialog", "..."))
        self.font_label.setText(_translate("FontAndColorDialog", "字体"))
        self.warning_background_color_label.setText(_translate("FontAndColorDialog", "警示背景色"))
        self.warning_background_color_toolButton.setText(_translate("FontAndColorDialog", "..."))
        self.font_color_toolButton.setText(_translate("FontAndColorDialog", "..."))
        self.content_background_color_toolButton.setText(_translate("FontAndColorDialog", "..."))
        self.font_toolButton.setText(_translate("FontAndColorDialog", "..."))
        self.cancel_pushButton.setText(_translate("FontAndColorDialog", "取消"))
        self.confirm_change_pushButton.setText(_translate("FontAndColorDialog", "确认修改"))
        self.confirm_change_pushButton.setShortcut(_translate("FontAndColorDialog", "Ctrl+Return"))

