# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shortCutSetDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_shortCutDialog(object):
    def setupUi(self, shortCutDialog):
        shortCutDialog.setObjectName("shortCutDialog")
        shortCutDialog.resize(346, 688)
        self.horizontalLayout = QtWidgets.QHBoxLayout(shortCutDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.hide_detail_company_label = QtWidgets.QLabel(shortCutDialog)
        self.hide_detail_company_label.setText("")
        self.hide_detail_company_label.setObjectName("hide_detail_company_label")
        self.gridLayout.addWidget(self.hide_detail_company_label, 6, 1, 1, 1)
        self.move_right_label = QtWidgets.QLabel(shortCutDialog)
        self.move_right_label.setText("")
        self.move_right_label.setObjectName("move_right_label")
        self.gridLayout.addWidget(self.move_right_label, 1, 1, 1, 1)
        self.recove_price_label = QtWidgets.QLabel(shortCutDialog)
        self.recove_price_label.setText("")
        self.recove_price_label.setObjectName("recove_price_label")
        self.gridLayout.addWidget(self.recove_price_label, 17, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(shortCutDialog)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 8, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(shortCutDialog)
        self.label_48.setObjectName("label_48")
        self.gridLayout.addWidget(self.label_48, 7, 0, 1, 1)
        self.sell_new_option_label = QtWidgets.QLabel(shortCutDialog)
        self.sell_new_option_label.setText("")
        self.sell_new_option_label.setObjectName("sell_new_option_label")
        self.gridLayout.addWidget(self.sell_new_option_label, 14, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(shortCutDialog)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 9, 0, 1, 1)
        self.add_price_label = QtWidgets.QLabel(shortCutDialog)
        self.add_price_label.setText("")
        self.add_price_label.setObjectName("add_price_label")
        self.gridLayout.addWidget(self.add_price_label, 16, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(shortCutDialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 17, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.location_up_label = QtWidgets.QLabel(shortCutDialog)
        self.location_up_label.setText("")
        self.location_up_label.setObjectName("location_up_label")
        self.horizontalLayout_12.addWidget(self.location_up_label)
        self.location_up_toolButton = QtWidgets.QToolButton(shortCutDialog)
        self.location_up_toolButton.setObjectName("location_up_toolButton")
        self.horizontalLayout_12.addWidget(self.location_up_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_12, 9, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.show_hide_company_label = QtWidgets.QLabel(shortCutDialog)
        self.show_hide_company_label.setText("")
        self.show_hide_company_label.setObjectName("show_hide_company_label")
        self.horizontalLayout_5.addWidget(self.show_hide_company_label)
        self.show_hide_company_toolButton = QtWidgets.QToolButton(shortCutDialog)
        self.show_hide_company_toolButton.setObjectName("show_hide_company_toolButton")
        self.horizontalLayout_5.addWidget(self.show_hide_company_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 1, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.location_down_label = QtWidgets.QLabel(shortCutDialog)
        self.location_down_label.setText("")
        self.location_down_label.setObjectName("location_down_label")
        self.horizontalLayout_13.addWidget(self.location_down_label)
        self.location_down_toolButton = QtWidgets.QToolButton(shortCutDialog)
        self.location_down_toolButton.setObjectName("location_down_toolButton")
        self.horizontalLayout_13.addWidget(self.location_down_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_13, 10, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.page_down_label = QtWidgets.QLabel(shortCutDialog)
        self.page_down_label.setText("")
        self.page_down_label.setObjectName("page_down_label")
        self.horizontalLayout_10.addWidget(self.page_down_label)
        self.page_down_toolButton = QtWidgets.QToolButton(shortCutDialog)
        self.page_down_toolButton.setObjectName("page_down_toolButton")
        self.horizontalLayout_10.addWidget(self.page_down_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_10, 7, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(shortCutDialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 16, 0, 1, 1)
        self.switch_behind_label = QtWidgets.QLabel(shortCutDialog)
        self.switch_behind_label.setText("")
        self.switch_behind_label.setObjectName("switch_behind_label")
        self.gridLayout.addWidget(self.switch_behind_label, 2, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.page_up_label = QtWidgets.QLabel(shortCutDialog)
        self.page_up_label.setText("")
        self.page_up_label.setObjectName("page_up_label")
        self.horizontalLayout_11.addWidget(self.page_up_label)
        self.page_up_toolButton = QtWidgets.QToolButton(shortCutDialog)
        self.page_up_toolButton.setObjectName("page_up_toolButton")
        self.horizontalLayout_11.addWidget(self.page_up_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_11, 8, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(shortCutDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(shortCutDialog)
        self.label_49.setObjectName("label_49")
        self.gridLayout.addWidget(self.label_49, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(shortCutDialog)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 12, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(shortCutDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(shortCutDialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(shortCutDialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 14, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(shortCutDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.location_right_label = QtWidgets.QLabel(shortCutDialog)
        self.location_right_label.setText("")
        self.location_right_label.setObjectName("location_right_label")
        self.horizontalLayout_15.addWidget(self.location_right_label)
        self.location_right_toolButton = QtWidgets.QToolButton(shortCutDialog)
        self.location_right_toolButton.setObjectName("location_right_toolButton")
        self.horizontalLayout_15.addWidget(self.location_right_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_15, 12, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(shortCutDialog)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 10, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.show_hide_detail_label = QtWidgets.QLabel(shortCutDialog)
        self.show_hide_detail_label.setText("")
        self.show_hide_detail_label.setObjectName("show_hide_detail_label")
        self.horizontalLayout_4.addWidget(self.show_hide_detail_label)
        self.show_hide_detail_toolButton = QtWidgets.QToolButton(shortCutDialog)
        self.show_hide_detail_toolButton.setObjectName("show_hide_detail_toolButton")
        self.horizontalLayout_4.addWidget(self.show_hide_detail_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(shortCutDialog)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 11, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(shortCutDialog)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(shortCutDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(shortCutDialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 15, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(shortCutDialog)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 13, 0, 1, 2)
        self.this_module_confirm_label = QtWidgets.QLabel(shortCutDialog)
        self.this_module_confirm_label.setText("")
        self.this_module_confirm_label.setObjectName("this_module_confirm_label")
        self.gridLayout.addWidget(self.this_module_confirm_label, 15, 1, 1, 1)
        self.switch_front_label = QtWidgets.QLabel(shortCutDialog)
        self.switch_front_label.setText("")
        self.switch_front_label.setObjectName("switch_front_label")
        self.gridLayout.addWidget(self.switch_front_label, 3, 1, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.location_left_label = QtWidgets.QLabel(shortCutDialog)
        self.location_left_label.setText("")
        self.location_left_label.setObjectName("location_left_label")
        self.horizontalLayout_14.addWidget(self.location_left_label)
        self.location_left_toolButton = QtWidgets.QToolButton(shortCutDialog)
        self.location_left_toolButton.setObjectName("location_left_toolButton")
        self.horizontalLayout_14.addWidget(self.location_left_toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_14, 11, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(shortCutDialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 18, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(shortCutDialog)
        self.pushButton.clicked.connect(shortCutDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(shortCutDialog)
        shortCutDialog.setTabOrder(self.show_hide_detail_toolButton, self.show_hide_company_toolButton)
        shortCutDialog.setTabOrder(self.show_hide_company_toolButton, self.page_down_toolButton)
        shortCutDialog.setTabOrder(self.page_down_toolButton, self.page_up_toolButton)
        shortCutDialog.setTabOrder(self.page_up_toolButton, self.location_up_toolButton)
        shortCutDialog.setTabOrder(self.location_up_toolButton, self.location_down_toolButton)
        shortCutDialog.setTabOrder(self.location_down_toolButton, self.location_left_toolButton)
        shortCutDialog.setTabOrder(self.location_left_toolButton, self.location_right_toolButton)

    def retranslateUi(self, shortCutDialog):
        _translate = QtCore.QCoreApplication.translate
        shortCutDialog.setWindowTitle(_translate("shortCutDialog", "Dialog"))
        self.label_30.setText(_translate("shortCutDialog", "向上翻页"))
        self.label_48.setText(_translate("shortCutDialog", "向下翻页"))
        self.label_29.setText(_translate("shortCutDialog", "定位最上"))
        self.label_7.setText(_translate("shortCutDialog", "溢价率恢复"))
        self.location_up_toolButton.setText(_translate("shortCutDialog", "..."))
        self.show_hide_company_toolButton.setText(_translate("shortCutDialog", "..."))
        self.location_down_toolButton.setText(_translate("shortCutDialog", "..."))
        self.page_down_toolButton.setText(_translate("shortCutDialog", "..."))
        self.label_8.setText(_translate("shortCutDialog", "溢价率+0.25%"))
        self.page_up_toolButton.setText(_translate("shortCutDialog", "..."))
        self.label_5.setText(_translate("shortCutDialog", "显/隐明细"))
        self.label_49.setText(_translate("shortCutDialog", "明细对公双隐"))
        self.label_12.setText(_translate("shortCutDialog", "定位最右"))
        self.label_3.setText(_translate("shortCutDialog", "页面向后切"))
        self.label.setText(_translate("shortCutDialog", "显示快捷键"))
        self.label_10.setText(_translate("shortCutDialog", "销售新期权"))
        self.label_2.setText(_translate("shortCutDialog", "<>向右平移按钮"))
        self.location_right_toolButton.setText(_translate("shortCutDialog", "..."))
        self.label_28.setText(_translate("shortCutDialog", "定位最下"))
        self.show_hide_detail_toolButton.setText(_translate("shortCutDialog", "..."))
        self.label_27.setText(_translate("shortCutDialog", "定位最左"))
        self.label_13.setText(_translate("shortCutDialog", "显/隐对公"))
        self.label_4.setText(_translate("shortCutDialog", "页面向前切"))
        self.label_9.setText(_translate("shortCutDialog", "本模块确认键"))
        self.label_11.setText(_translate("shortCutDialog", "操作快捷键"))
        self.location_left_toolButton.setText(_translate("shortCutDialog", "..."))
        self.pushButton.setText(_translate("shortCutDialog", "确认更改"))
        self.pushButton.setShortcut(_translate("shortCutDialog", "Ctrl+Return"))

